DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS machine;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE machine (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  lookup_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ip TEXT NOT NULL,
  last_seen TIMESTAMP NOT NULL,
  FOREIGN KEY (lookup_id) REFERENCES user (id)
);
